%% WORKING DIRECTORY
    % Change le répertoire de travail
        userPath = userpath ;
        %userPath = userPath(1:end-1) ; % enlève le point virgule
        %cd([userPath,'/THESE/WORK_IN_PROGRESS'])
        cd(userPath)
    % INCLUSION DES LIBRAIRIES PERSO
        addpath(genpath(userPath))
    % NE PAS INCLURE WIP (Ca fait ramer Matlab...)
        %rmpath(genpath([userPath,'/THESE/WORK_IN_PROGRESS']))
        clear('userPath')
        
%% COMMAND WINDOW
    format short g


%% FIGURES
    % Fenêtre
        set(0,'DefaultFigureColor','w')
        set(0,'DefaultFigureColormap',jet(1000))
        
    % Axes
        set(0,'DefaultTextInterpreter', 'latex')
        set(0,'DefaultLegendInterpreter', 'latex')
        set(0,'DefaultAxesTickLabelInterpreter', 'latex')
        
    % Place les figures en plein ecran sur l'ecran de droite (le dernier
    % sur la liste)
        screenposition = get(groot,'monitorpositions') ; % [1921 301 1600 821] ;%
        figposition = screenposition(end,:)-[0 0 0 79] ;
        
    % Set les valeurs par défaut
        set(0, ...
        'defaultfigureposition',figposition,...
        'DefaultFigureColor', 'white', ...
        'DefaultFigurePaperType', 'A4', ...
        'DefaultAxesColor', 'none', ...
        ...'DefaultAxesDrawmode', 'fast', ...
        'DefaultAxesFontUnits', 'pixels', ...
        'DefaultAxesFontSize', 20, ...
        'DefaultAxesFontAngle', 'normal', ...
        'DefaultAxesFontName', 'Times', ...
        'DefaultAxesGridLineStyle', ':', ...
        'DefaultAxesInterruptible', 'on', ...
        'DefaultAxesLayer', 'Bottom', ...
        'DefaultAxesNextPlot', 'add', ...
        'DefaultAxesUnits', 'normalized', ...
        'DefaultAxesXcolor', [0, 0, 0], ...
        'DefaultAxesYcolor', [0, 0, 0], ...
        'DefaultAxesZcolor', [0, 0, 0], ...
        'DefaultAxesVisible', 'on', ...
        ...'DefaultLineColor', 'Red', ...
        'DefaultLineLineStyle', '-', ...
        'DefaultLineLineWidth', 2, ...
        'DefaultLineMarker', 'none', ...
        'DefaultLineMarkerSize', 8, ...
        'DefaultTextColor', [0, 0, 0], ...
        'DefaultTextFontUnits', 'pixels', ...
        'DefaultTextFontSize', 25, ...
        'DefaultTextFontName', 'Times', ...
        'DefaultTextVerticalAlignment', 'middle', ...
        'DefaultTextHorizontalAlignment', 'center',...
        'DefaultAxesLooseInset',[0.02,0.02,0.02,0.02],...
        'DefaultLegendEdgeColor','none',...
        'DefaultlegendLocation','NorthEast');
    
    
    %% DEBUG
        %dbstop if error
        
        
    %% NETTOYAGE
        clc 
        clear all
        close all
        
    %% GENERATEUR DE NOMBRES ALEATOIRES
        rng('shuffle')